server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /temp

  datasource:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true